### ISSUE TITLE
pegtl-2.1.3 doesn't build with gcc-7.1

### ISSUE THREAD

**Issue by junghans** [taocpp/PEGTL#64]
```
[ 22%] Building CXX object src/test/pegtl/CMakeFiles/internal_file_opener.dir/internal_file_opener.cpp.o
cd /var/tmp/portage/dev-libs/pegtl-2.1.3/work/pegtl-2.1.3_build/src/test/pegtl && /usr/lib64/ccache/bin/x86_64-pc-linux-gnu-g++   -I/var/tmp/portage/dev-libs/pegtl-2.1.3/work/PEGTL-2.1.3/include   -DNDEBUG -O2 -pipe -march=native -fomit-frame-pointer   -pedantic -Wall -Wextra -Wshadow -Werror -std=c++11 -o CMakeFiles/internal_file_opener.dir/internal_file_opener.cpp.o -c /var/tmp/portage/dev-libs/pegtl-2.1.3/work/PEGTL-2.1.3/src/test/pegtl/internal_file_opener.cpp
/var/tmp/portage/dev-libs/pegtl-2.1.3/work/PEGTL-2.1.3/src/test/pegtl/contrib_raw_string.cpp:59:42: error: declaration of template parameter ‘Rule’ shadows template parameter
       template< typename Rule, template< typename Rule > class Action, unsigned M, unsigned N >
                                          ^~~~~~~~
/var/tmp/portage/dev-libs/pegtl-2.1.3/work/PEGTL-2.1.3/src/test/pegtl/contrib_raw_string.cpp:59:17: note: template parameter ‘Rule’ declared here
       template< typename Rule, template< typename Rule > class Action, unsigned M, unsigned N >
                 ^~~~~~~~
make[2]: *** [src/test/pegtl/CMakeFiles/contrib_raw_string.dir/build.make:63: src/test/pegtl/CMakeFiles/contrib_raw_string.dir/contrib_raw_string.cpp.o] Error 1
```
Details here: [build.txt](https://github.com/taocpp/PEGTL/files/1106577/build.txt)

**Comment by d-frey** [comment]
Yes, sorry, it is already fixed with the commit that followed the release of 2.1.3. The problem only affects one of our test sources, so the library itself it fully functional. I know, not a good excuse ;-)

I don't want to rush into the next small issue, so I created an (internal) release checklist that I'll review with Colin before we can finally release a stable version 2.1.4 without further small issues and that should help us to avoid similar mistakes in the future.

**Comment by d-frey** [comment]
Release 2.1.4 is available now. Sorry for the inconvenience.

**Comment by junghans** [comment]
Added in LLNL/spack@7e4e47df760fc5b4d925c40bd1c6d89c63ab7002

**Comment by junghans** [comment]
And in gentoo/gentoo@fa4f124019f284cfef66ecd02744cede3f8db071.
