### ISSUE TITLE
Question: Parse Tree Parse Function Signature in PEGTL 3/2.7.x?

### ISSUE THREAD

**Issue by sanssecours** [taocpp/PEGTL#143]
# Steps to Reproduce the Issue

1. Download the following archive: [Tree Construction.zip](https://github.com/taocpp/PEGTL/files/2754825/Tree.Construction.zip)
2. Extract the directory stored in the archive somewhere
3. Change into the extracted directory
4. Run `make`

# Expected Result 

Make should be able to compile the file `yaypeg.cpp`.

# Actual Result

The compiler (Clang on my machine) fails to compile the code printing the following error message:

```
[1/2] Building CXX object CMakeFiles/yaypeg.dir/Source/yaypeg.cpp.o
FAILED: CMakeFiles/yaypeg.dir/Source/yaypeg.cpp.o
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++   -I/usr/local/include -std=gnu++1z -MD -MT CMakeFiles/yaypeg.dir/Source/yaypeg.cpp.o -MF CMakeFiles/yaypeg.dir/Source/yaypeg.cpp.o.d -o CMakeFiles/yaypeg.dir/Source/yaypeg.cpp.o -c ../Source/yaypeg.cpp
In file included from ../Source/yaypeg.cpp:3:
In file included from /usr/local/include/tao/pegtl.hpp:10:
In file included from /usr/local/include/tao/pegtl/internal/../ascii.hpp:11:
In file included from /usr/local/include/tao/pegtl/internal/rules.hpp:7:
In file included from /usr/local/include/tao/pegtl/internal/action.hpp:9:
/usr/local/include/tao/pegtl/internal/duseltronik.hpp:61:16: error: no matching function for call to 'start'
               Control< Rule >::start( static_cast< const Input& >( in ), st... );
               ^~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/tao/pegtl/contrib/../normal.hpp:82:80: note: in instantiation of function template specialization 'tao::pegtl::internal::duseltronik<tao::pegtl::success, tao::pegtl::apply_mode::ACTION, tao::pegtl::rewind_mode::REQUIRED, nothing, type, tao::pegtl::dusel_mode::CONTROL>::match<tao::pegtl::file_input<tao::pegtl::tracking_mode::IMMEDIATE, tao::pegtl::ascii::eol::lf_crlf>, State &, tao::pegtl::parse_tree::internal::state<tao::pegtl::parse_tree::node> &>' requested here
            return internal::duseltronik< Rule, A, M, Action, Control, mode >::match( in, st... );
                                                                               ^
/usr/local/include/tao/pegtl/contrib/../parse.hpp:31:43: note: in instantiation of function template specialization 'tao::pegtl::normal<tao::pegtl::success>::match<tao::pegtl::apply_mode::ACTION, tao::pegtl::rewind_mode::REQUIRED, nothing, type, tao::pegtl::file_input<tao::pegtl::tracking_mode::IMMEDIATE, tao::pegtl::ascii::eol::lf_crlf>, State &, tao::pegtl::parse_tree::internal::state<tao::pegtl::parse_tree::node> &>' requested here
         return Control< Rule >::template match< A, M, Action, Control >( in, st... );
                                          ^
/usr/local/include/tao/pegtl/contrib/parse_tree.hpp:774:39: note: in instantiation of function template specialization 'tao::pegtl::parse<tao::pegtl::success, nothing, internal::make_control<node, selector, normal>::type, tao::pegtl::apply_mode::ACTION, tao::pegtl::rewind_mode::REQUIRED, tao::pegtl::file_input<tao::pegtl::tracking_mode::IMMEDIATE, tao::pegtl::ascii::eol::lf_crlf> &, State &, tao::pegtl::parse_tree::internal::state<tao::pegtl::parse_tree::node> &>' requested here
            if( !TAO_PEGTL_NAMESPACE::parse< Rule, Action, internal::make_control< Node, Selector, Control >::template type >( in, st..., state ) ) {
                                      ^
/usr/local/include/tao/pegtl/contrib/parse_tree.hpp:789:20: note: in instantiation of function template specialization 'tao::pegtl::parse_tree::parse<tao::pegtl::success, tao::pegtl::parse_tree::node, selector, nothing, normal, tao::pegtl::file_input<tao::pegtl::tracking_mode::IMMEDIATE, tao::pegtl::ascii::eol::lf_crlf> &, State &>' requested here
            return parse< Rule, node, Selector, Action, Control >( in, st... );
                   ^
../Source/yaypeg.cpp:18:19: note: in instantiation of function template specialization 'tao::pegtl::parse_tree::parse<tao::pegtl::success, selector, nothing, normal, tao::pegtl::file_input<tao::pegtl::tracking_mode::IMMEDIATE, tao::pegtl::ascii::eol::lf_crlf> &, State &>' requested here
      parse_tree::parse<success, selector, nothing, normal>(input, state);
                  ^
/usr/local/include/tao/pegtl/contrib/parse_tree.hpp:623:28: note: candidate function not viable: no known conversion from 'State' to 'state<tao::pegtl::parse_tree::node> &' for 2nd argument
               static void start( const Input& in, States&&... st, state< Node >& state )
                           ^
In file included from ../Source/yaypeg.cpp:3:
In file included from /usr/local/include/tao/pegtl.hpp:10:
In file included from /usr/local/include/tao/pegtl/internal/../ascii.hpp:11:
In file included from /usr/local/include/tao/pegtl/internal/rules.hpp:7:
In file included from /usr/local/include/tao/pegtl/internal/action.hpp:9:
/usr/local/include/tao/pegtl/internal/duseltronik.hpp:64:19: error: no matching function for call to 'success'
                  Control< Rule >::success( static_cast< const Input& >( in ), st... );
                  ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/tao/pegtl/contrib/parse_tree.hpp:631:28: note: candidate function not viable: no known conversion from 'State' to 'state<tao::pegtl::parse_tree::node> &' for 2nd argument
               static void success( const Input& in, States&&... st, state< Node >& state )
                           ^
In file included from ../Source/yaypeg.cpp:3:
In file included from /usr/local/include/tao/pegtl.hpp:10:
In file included from /usr/local/include/tao/pegtl/internal/../ascii.hpp:11:
In file included from /usr/local/include/tao/pegtl/internal/rules.hpp:7:
In file included from /usr/local/include/tao/pegtl/internal/action.hpp:9:
/usr/local/include/tao/pegtl/internal/duseltronik.hpp:67:16: error: no matching function for call to 'failure'
               Control< Rule >::failure( static_cast< const Input& >( in ), st... );
               ^~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/include/tao/pegtl/contrib/parse_tree.hpp:644:28: note: candidate function not viable: no known conversion from 'State' to 'state<tao::pegtl::parse_tree::node> &' for 2nd argument
               static void failure( const Input& in, States&&... st, state< Node >& state ) noexcept( noexcept( Control< Rule >::failure( in, st... ) ) && noexcept( std::declval< node& >().template failure< Rule >( in, st... ) ) )
                           ^
3 errors generated.
ninja: build stopped: subcommand failed.
```

.

# Additional Information

The example in the archive `yaypeg.cpp`:

```cpp
#include <string>

#include <tao/pegtl.hpp>
#include <tao/pegtl/contrib/parse_tree.hpp>

using namespace tao::pegtl;

template <typename Rule> struct selector : std::true_type {};

struct State {};

int main(int argc, char *argv[]) {
  std::string filename = argv[1];
  file_input<> input{filename};

  State state;
  auto root =
      parse_tree::parse<success, selector, nothing, normal>(input, state);

  return 0;
}
```

works fine in PEGTL `2.7.1`. However, since commit d64bf1d the code does not compile any more. As far as I can tell PEGLT now assumes that `state` contains  a parse tree node, and not a custom state used during the parsing process. Can you please tell me how I need to update the statement

```cpp
auto root =
      parse_tree::parse<success, selector, nothing, normal>(input, state);
```

for the code to also work in the latest version of PEGTL?

# System Information

- macOS `10.14.2`
- Clang (Apple LLVM version `10.0.0`)
- PEGTL `2.7.x`/`master`

**Comment by d-frey** [comment]
Maybe I broke something else, but it seems that the just-committed fix works. Please check if HEAD works for you, thanks.

**Comment by d-frey** [comment]
Every problem can be solved by another layer of indirection :)

It should work now without messing with the argument order for the `match`-methods.

**Comment by sanssecours** [comment]
Thank you very much for working on this. The example above does now work on my system.

I do have another question though. In PEGTL `2.7.1` the following code:

```cpp
#include <string>

#include <tao/pegtl.hpp>
#include <tao/pegtl/contrib/parse_tree.hpp>

using namespace tao::pegtl;

template <typename Rule> struct selector : std::true_type {};

struct State {};

template <typename Rule> struct work : nothing<Rule> {};

template <> struct work<success> {
  template <typename Input> static void apply(const Input &, State &state) {}
};

int main(int argc, char *argv[]) {
  std::string filename = argv[1];
  file_input<> input{filename};

  State state;
  auto root = parse_tree::parse<success, selector, work, normal>(input, state);

  return 0;
}
```

compiles without any problems. In the `master` version of PEGTL it does not work anymore. As far as I can tell, this is also a consequence of commit d64bf1d. However, even I update the action `work` to:

```cpp
template <> struct work<success> {
  template <typename Input, typename... States>
  static void apply(const Input &, State &state, States &&...) {}
};
```

, the code still fails to compile. Can you please tell me what I am doing wrong?

**Comment by d-frey** [comment]
I forget the template parameter in `apply`/`apply0`, this should be fixed now. The updated `work` version you posted should work now.

**Comment by d-frey** [comment]
FWIW, I just committed some fixes to the Duseltronik, which replace a short-cut for detecting `apply`/`apply0` with the proper method of doing so. This now allows you to change the signature of `work` back to what it should be:

    template <> struct work<success> {
      template <typename Input> static void apply(const Input &, State &state) {}
    };

should work just fine now, the extra parameter when creating a parse tree is gone. 🥳
