### ISSUE TITLE
PEGTL fails to build with GCC 16.1

### ISSUE THREAD

**Issue by tippfehlr** [taocpp/PEGTL#382]
```
/home/jonathan/code/other/PEGTL/include/tao/pegtl/internal/../demangle.hpp:101:26: error: static assertion failed
  101 |       static_assert( end != std::string_view::npos );
      |                      ~~~~^~~~~~~~~~~~~~~~~~~~~~~~~
  • the comparison reduces to ‘(18446744073709551615 != 18446744073709551615)’
```

[build.log](https://github.com/user-attachments/files/28439486/build.log)

**Comment by ColinH** [comment]
It compiles with GCC 15? I still need to install GCC 16 to take a closer look at what changed.

**Comment by tippfehlr** [comment]
Yes, it builds with GCC 15.2.1. My GCC is 16.1.1, specifically the Arch version (16.1.1+r12+g301eb08fa2c5-1)

**Comment by ColinH** [comment]
Reproduced with GCC 16.1.0 on Debian testing. Something changed regarding how template parameters appear in `__PRETTY_FUNCTION__` .

**Comment by ColinH** [comment]
This is a GCC bug regarding `__PRETTY_FUNCTION__` that was in 9.1 and 9.2, fixed in 9.3, back again in 16.1.

https://gcc.gnu.org/bugzilla/show_bug.cgi?id=91155

**Comment by ColinH** [comment]
As quick fix I enabled the same fallback for GCC 16 as for GCC 9.1 and 9.2, i.e. to return `typeid( T ).name()` instead of attempting to use the demangle heuristic. Hope that works for you until GCC fixes this again.

**Comment by tippfehlr** [comment]
Thanks for the quick fix! The demangle test fails now, but I’ll add the same gcc == 16 check there too.
